### ISSUE TITLE
Less pretty

### ISSUE THREAD

**Issue by jalenzz** [jalenchuh/gridea-theme-dark#5]

**Comment by jalenzz** [comment]
example:

```less
// before
a {
  color: #d2d2d2;
  text-decoration: none;
}

a:hover {
  color: #699be9;
  text-decoration: underline;
}

// after
a {
  color: #d2d2d2;
  text-decoration: none;

  &:hover {
    color: #699be9;
    text-decoration: underline;
  }
}
```
